services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - proxy_network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_PASSWORD
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`$GRAFANA_HOSTNAME`)"
      - "traefik.http.routers.grafana.entrypoints=${TRAEFIK_ENTRYPOINTS:-websecure}"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - proxy_network
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`$PROMETHEUS_HOSTNAME`)"
      - "traefik.http.routers.prometheus.entrypoints=${TRAEFIK_ENTRYPOINTS:-websecure}"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  loki:
    image: 'grafana/loki'
    container_name: loki
    networks:
      - proxy_network
    command: '--config.file=/mnt/config/config.yaml'
    configs:
      - source: loki-config.yaml
        target: /mnt/config/config.yaml
    volumes:
      - loki_data:/loki:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`$LOKI_HOSTNAME`)"
      - "traefik.http.routers.loki.entrypoints=${TRAEFIK_ENTRYPOINTS:-websecure}"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"

configs:
  prometheus.yml:
    content: |
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
        scrape_protocols:
        - OpenMetricsText1.0.0
        - OpenMetricsText0.0.1
        - PrometheusText1.0.0
        - PrometheusText0.0.4
        evaluation_interval: 15s
      runtime:
        gogc: 75
      alerting:
        alertmanagers:
        - follow_redirects: true
          enable_http2: true
          scheme: http
          timeout: 10s
          api_version: v2
          static_configs:
          - targets: []
      scrape_configs:
        - job_name: prometheus
          honor_timestamps: true
          track_timestamps_staleness: false
          scrape_interval: 15s
          scrape_timeout: 10s
          scrape_protocols:
            - OpenMetricsText1.0.0
            - OpenMetricsText0.0.1
            - PrometheusText1.0.0
            - PrometheusText0.0.4
          always_scrape_classic_histograms: false
          convert_classic_histograms_to_nhcb: false
          metrics_path: /metrics
          scheme: http
          enable_compression: true
          metric_name_validation_scheme: utf8
          metric_name_escaping_scheme: allow-utf-8
          follow_redirects: true
          enable_http2: true
          static_configs:
            - targets:
                - localhost:9090
              labels:
                app: prometheus
        - job_name: incus
          metrics_path: '/1.0/metrics'
          scheme: 'https'
          static_configs:
            - targets: ['10.120.135.1:8444']
          tls_config:
            insecure_skip_verify: true
      #      ca_file: 'tls/server.crt'
      #      cert_file: 'tls/metrics.crt'
      #      key_file: 'tls/metrics.key'
      #      # XXX: server_name is required if the target name
      #      #      is not covered by the certificate (not in the SAN list)
      #      server_name: 'foo'
      otlp:
        translation_strategy: UnderscoreEscapingWithSuffixes

  loki-config.yaml:
    content: |
      ---
      auth_enabled: false
      server:
        http_listen_port: 3100
      common:
        instance_addr: 127.0.0.1
        path_prefix: /loki
        storage:
          filesystem:
            chunks_directory: /loki/chunks
            rules_directory: /loki/rules
        replication_factor: 1
        ring:
          kvstore:
            store: inmemory
      schema_config:
        configs:
          - from: 2020-10-24
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
      limits_config:
        # NOTE: Data Retention is set to 7 days.
        #       This is the default value and can be changed
        retention_period: 168h
        ingestion_rate_mb: 4
        ingestion_burst_size_mb: 6
        max_streams_per_user: 10000
        max_line_size: 256000
      ruler:
        alertmanager_url: http://localhost:9093

volumes:
  grafana_data:
  prometheus_data:
  loki_data:
  promtail_log:
  promtail_data:

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true
