apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: netbird
namespace: my-netbird
resources:
- dashboard.yml
- signal.yml
- management.yml
- service.yml
- ingress.yml
- namespace.yml
# configure your netbird relay
configMapGenerator:
- name: relay-cm
  literals:
  - NB_LOG_LEVEL=info
  - NB_EXPOSED_ADDRESS=rels://relay.public.127.0.0.1.sslip.io:443
secretGenerator:
- name: relay-secrets
  literals:
  - NB_AUTH_SECRET="openssl rand -base64 32 | sed 's/=//g'"
images:
  - name: netbirdio/dashboard
    newTag: latest
  - name: netbirdio/signal
    newTag: latest
  - name: netbirdio/management
    newTag: latest
  - name: coturn/coturn
    newTag: latest
  - name: netbirdio/relay
    newTag: latest