services:
  minio:
    restart: always
    image: quay.io/minio/minio
    container_name: minio
    networks:
      - proxy_network
    command: server /data --console-address ":9090"
    user: "$UID:$GID"
    environment:
     - MINIO_ROOT_USER=$MINIO_ROOT_USER
     - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
    volumes:
      - minio_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=$PROXY_NETWORK"
      # web console
      - "traefik.http.routers.minio-console.tls=true"
      - "traefik.http.routers.minio-console.rule=Host(`$UI_PUBLIC_HOSTNAME`)"
      - "traefik.http.routers.minio-console.entrypoints=$UI_ENTRYPOINTS"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9090"
      # s3 endpoint
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.rule=Host(`$PUBLIC_HOSTNAME`)"
      - "traefik.http.routers.minio.entrypoints=$PUBLIC_ENTRYPOINTS"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

volumes:
  minio_data:

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true
