apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <MYTELEPORTUSER>-crb
subjects:
- kind: User
  name: <MYTELEPORTUSER>
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin # bad idea, example only
  apiGroup: rbac.authorization.k8s.io