apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: netbird-relay
namespace: my-netbird
resources:
- ../zitadel
- relay.yml
- service.yml
- ingress.yml
patches:
- target:
    kind: Deployment
    name: coturn
  path: patch-no-coturn.yml
- target:
    kind: StatefulSet
    name: management
  path: patch-coturn-domain.yml