services:
  agent:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
      - /etc/hosts:/etc/hosts
      - /etc/timezone/:/etc/timezone
      - portainer_agent_data:/data
    restart: always
    environment:
      - EDGE=1
      - EDGE_ID=794615bd-9b72-4af8-bce1-f8bcc663fef4
      - EDGE_KEY=$EDGE_KEY
      - EDGE_INSECURE_POLL=1
    container_name: portainer_edge_agent
    image: portainer/agent:$IMAGE_TAG

volumes:
  portainer_agent_data:
