apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: netbird
namespace: my-netbird
resources:
- ../../base
- configmap.yml
configMapGenerator:
- name: netbird-cm
  literals:
  - NETBIRD_DOMAIN=skynet.public.127.0.0.1.sslip.io
  - NETBIRD_MGMT_DNS_DOMAIN=sky.net
  - NETBIRD_DISABLE_ANONYMOUS_METRICS=true
  - NETBIRD_STORE_CONFIG_ENGINE=sqlite
  - NETBIRD_TOKEN_SOURCE=idToken
  - NETBIRD_AUTH_AUTHORITY=auth.127.0.0.1.sslip.io
  - NETBIRD_AUTH_SUPPORTED_SCOPES=openid profile email offline_access api
  - NETBIRD_AUTH_CLIENT_ID=248375388709912658@MYZITADEL_PROJECT
  - NETBIRD_IDP_MGMT_CLIENT_ID=netbird # service account user
  - NETBIRD_MGMT_DISABLE_SINGLE_ACCOUNT_MODE=false
secretGenerator:
- name: netbird-secrets
  literals:
  - NETBIRD_IDP_MGMT_CLIENT_SECRET=MYCLIENTSECRET # service account secret
  - NETBIRD_DATASTORE_ENC_KEY="openssl rand -base64 32 | sed 's/=//g'"
  - NETBIRD_AUTH_CLIENT_SECRET=""
