x-default: &default
  restart: 'always'
  logging:
    driver: 'json-file'
    options:
      max-size: '500m'
      max-file: '2'

services:  
  traefik:
    <<: *default
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "80:80"
      - "443:443"
    security_opt:
      - no-new-privileges:true
    command:
      - --configFile=/etc/traefik/traefik_config.yaml
    environment:      
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.yaml:/etc/traefik/traefik_config.yaml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik/logs:/var/log/traefik
