services:
  oauth2proxy:
    restart: unless-stopped
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2proxy
    networks:
      - proxy_network
    environment:
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_PROVIDER=$OAUTH2_PROVIDER
      - OAUTH2_PROXY_CLIENT_ID=$CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET=$CLIENT_SECRET
      - OAUTH2_PROXY_EMAIL_DOMAINS=$TRUSTED_EMAIL_DOMAINS
      # - OAUTH2_PROXY_REDIRECT_URL=https://$PUBLIC_HOSTNAME/oauth2/callback
      - OAUTH2_PROXY_WHITELIST_DOMAINS=$WHITELIST_DOMAINS # allow Redirection back to original target
      - OAUTH2_PROXY_COOKIE_SECRET=$COOKIE_SECRET
      # COOKIE
      - OAUTH2_PROXY_COOKIE_DOMAINS=$COOKIE_DOMAINS # Cookie can be used on subdomain
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST=true
      - OAUTH2_PROXY_COOKIE_CSRF_EXPIRE=5m
      # Azure
      - OAUTH2_PROXY_AZURE_TENANT=$AZURE_TENANT
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/$AZURE_TENANT/v2.0
      # Keycloak
      # - OAUTH2_PROXY_PROVIDER=oidc
      # - OAUTH2_PROXY_OIDC_ISSUER_URL=https://auth.example.com/realms/master
      # Page Template
      # - OAUTH2_PROXY_BANNER=-
      # - OAUTH2_PROXY_FOOTER=-
      # - OAUTH2_PROXY_CUSTOM_SIGN_IN_LOGO=-
      # - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true # DEV
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authproxy.rule=Host(`$PUBLIC_HOSTNAME`)"
      - "traefik.http.routers.authproxy.rule=(Host(`$PUBLIC_HOSTNAME`) && PathPrefix(`/oauth2/`)) || (PathPrefix(`/oauth2/`))"
      - "traefik.http.services.authproxy.loadbalancer.server.port=4180"
      # Create auth middlewares
      - "traefik.http.middlewares.fwoauth-verify.forwardAuth.address=http://oauth2proxy:4180/oauth2/auth"
      - "traefik.http.middlewares.fwoauth-verify.forwardAuth.trustForwardHeader=true"
      - "traefik.http.middlewares.fwoauth-signin.errors.service=authproxy"
      - "traefik.http.middlewares.fwoauth-signin.errors.status=401"
      - "traefik.http.middlewares.fwoauth-signin.errors.query=/oauth2/sign_in?rd={url}"
      - "traefik.http.middlewares.fwoauth.chain.middlewares=fwoauth-signin,fwoauth-verify"

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true