http:
  routers:
    traefik-dashboard:
      rule: Host(`traefik.yourdomain.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      entryPoints:
        - "websecure"
      service: api@internal
    nextcloud:
      rule: "Host(`cloud.mydomain.net`)"
      entrypoints:
        - "websecure"
      service: nextcloud
      middlewares:
        - nextcloud-chain
    ollama:
      rule: "Host(`ollama.127.0.0.1.nip.io`)"
      entrypoints:
        - "websecure"
      service: ollama

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://192.168.55.51:11000"
    ollama:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:11434"

  middlewares:
    nextcloud-secure-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
    https-redirect:
      redirectscheme:
        scheme: https
    nextcloud-chain:
      chain:
        middlewares:
          - https-redirect
          - nextcloud-secure-headers