services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    ports:
      - 8080:8080
    environment:
      AIO_DISABLE_BACKUP_SECTION: true
      APACHE_PORT: 11000
      # APACHE_IP_BINDING: 0.0.0.0
      # APACHE_ADDITIONAL_NETWORK: $PROXY_NETWORK #frontend_net
      # COLLABORA_SECCOMP_DISABLED: false
      NEXTCLOUD_DATADIR: /mnt/nextcloud-data/ncaio-data
      NEXTCLOUD_MOUNT: /mnt/nextcloud-data
      # NEXTCLOUD_UPLOAD_LIMIT: 16G
      # NEXTCLOUD_MAX_TIME: 3600
      # NEXTCLOUD_STARTUP_APPS: deck twofactor_totp tasks calendar contacts notes
      # NEXTCLOUD_ADDITIONAL_APKS: imagemagick
      # NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS: imagick
      # NEXTCLOUD_ENABLE_DRI_DEVICE: true
      SKIP_DOMAIN_VALIDATION: false

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer