x-default: &default
  restart: 'always'
  logging:
    driver: 'json-file'
    options:
      max-size: '500m'
      max-file: '2'

services:
  beszel:
    <<: *default
    image: henrygd/beszel    
    networks:
      - proxy_network      
    environment:
      - TZ=Europe/Berlin
      - APP_URL=https://$PUBLIC_HOSTNAME
      - DISABLE_PASSWORD_AUTH=$DISABLE_PASSWORD_AUTH
    volumes:
      - beszel_data:/beszel_data      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`$PUBLIC_HOSTNAME`)"
      - "traefik.http.routers.beszel.entrypoints=${TRAEFIK_ENTRYPOINTS:-websecure}"
      - "traefik.http.routers.beszel.service=beszel"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"

volumes:
  beszel_data:  

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true
  backend_network:
