services:
  dashboard:
    environment:
      - AUTH_CLIENT_SECRET=
      - AUTH_AUDIENCE=$NETBIRD_AUTH_CLIENT_ID
      - AUTH_AUTHORITY=https://login.microsoftonline.com/$AZ_TENANT_ID/v2.0

configs:
  management.json:
    content: |
      {
        "Relay": {
          "Addresses": ["rels://$RELAY_DOMAIN:443"],
          "CredentialsTTL": "24h",
          "Secret": "$RELAY_SECRET"
        },
        "Signal": {
            "Proto": "https",
            "URI": "$NETBIRD_DOMAIN:443",
            "Username": "",
            "Password": null
        },
        "Datadir": "/var/lib/netbird/",
        "DataStoreEncryptionKey": "$NETBIRD_DATASTORE_ENC_KEY",
        "StoreConfig": {
            "Engine": "$NETBIRD_STORE_CONFIG_ENGINE"
        },
        "HttpConfig": {
            "AuthAudience": "$NETBIRD_AUTH_CLIENT_ID",
            "AuthUserIDClaim": "$NETBIRD_AUTH_USER_ID_CLAIM",
            "IdpSignKeyRefreshEnabled": $NETBIRD_MGMT_IDP_SIGNKEY_REFRESH,
            "OIDCConfigEndpoint":"https://login.microsoftonline.com/$AZ_TENANT_ID/v2.0/.well-known/openid-configuration"
        },
        "IdpManagerConfig": {
            "ManagerType": "$NETBIRD_MGMT_IDP",
            "ClientConfig": {
                "Issuer": "https://login.microsoftonline.com/$AZ_TENANT_ID/v2.0",
                "TokenEndpoint": "https://login.microsoftonline.com/$AZ_TENANT_ID/oauth2/v2.0/token",
                "ClientID": "$NETBIRD_AUTH_CLIENT_ID",
                "ClientSecret": "$NETBIRD_AUTH_CLIENT_SECRET",
                "GrantType": "client_credentials"
            },
            "ExtraConfig": {
                "GraphApiEndpoint":"https://graph.microsoft.com/v1.0",
                "ObjectId":"$AZ_OBJECT_ID"
            },
            "Auth0ClientCredentials": null,
            "AzureClientCredentials": null,
            "KeycloakClientCredentials": null,
            "ZitadelClientCredentials": null
        },
        "DeviceAuthorizationFlow": {
            "Provider": "none",
            "ProviderConfig": {
              "Audience": "$NETBIRD_AUTH_CLIENT_ID",
              "AuthorizationEndpoint": "",
              "ClientID": "$NETBIRD_AUTH_CLIENT_ID",
              "ClientSecret": "$NETBIRD_AUTH_CLIENT_SECRET",
              "Scope": "openid",
              "UseIDToken": false,
              "RedirectURLs": null
            }
        },
        "PKCEAuthorizationFlow": {
            "ProviderConfig": {
                "Audience": "$NETBIRD_AUTH_CLIENT_ID",
                "ClientID": "$NETBIRD_AUTH_CLIENT_ID",
                "ClientSecret": "$NETBIRD_AUTH_CLIENT_SECRET",
                "Domain": "",
                "Scope": "$NETBIRD_AUTH_SUPPORTED_SCOPES",
                "RedirectURLs": [
                  "http://localhost:53000",
                  "https://$NETBIRD_DOMAIN/auth",
                  "https://$NETBIRD_DOMAIN/silent-auth"
                ],
                "UseIDToken": false
            }
        }
      }