services:
  mysql:
    image: docker.io/library/mysql:8.3
    container_name: mysql
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=gitea
      - MYSQL_DATABASE=gitea
      - MYSQL_PASSWORD=$GITEA_DB_PASS

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
    #   - "3000:3000"
      - "$GITTEA_SSH_PORT:22"
    networks:
      - backend
      - proxy_network
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mysql:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=$GITEA_DB_PASS
      - GITEA__server__SSH_PORT=${GITTEA_SSH_PORT:-2221}
      - GITEA__server__ROOT_URL=https://$PUBLIC_HOSTNAME
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=$PROXY_NETWORK"
      - "traefik.http.routers.gitea.rule=Host(`$PUBLIC_HOSTNAME`)"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

volumes:
  mysql_data:
  gitea_data:

networks:
  backend:
  proxy_network:
    name: $PROXY_NETWORK
    external: true
