services:
  teleport:
    # image: public.ecr.aws/gravitational/teleport:$IMAGETAG
    image: public.ecr.aws/gravitational/teleport-distroless:$IMAGETAG # if you don't need ssh support
    container_name: teleport-agent
    restart: unless-stopped
    networks:
      - proxy_network
    configs:
      - source: teleport.yaml
        target: /etc/teleport/teleport.yaml
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - data:/var/lib/teleport
      # if you need to store ssh keys etc...
      # - ssh_drive:/root

configs:
  teleport.yaml:
    content: |
      version: v3
      teleport:
        nodename: ${NODENAME:-docker-agent}
        data_dir: /var/lib/teleport
        join_params:
          token_name: $TELEPORT_TOKEN
          method: token
        proxy_server: $TELEPORT_PROXY
        log:
          output: stderr
          severity: INFO
          format:
            output: text
        ca_pin: $TELEPORT_CA_PIN
        diag_addr: ""
      auth_service:
        enabled: "no"
      ssh_service:
        enabled: "no"
      proxy_service:
        enabled: "no"
      app_service:
        enabled: no
        # apps:
        # - name: "example app"
        #   uri: "http://example-app-url"
        #   insecure_skip_verify: true # optionaly
        #   public_addr: "mypublicnamewospacesordashes.$DOMAINNAME" # optionaly
        #   labels:  # optionaly
        #     customer: my_customer
        #     app: remotely
        #   rewrite:  # optionaly
        #     headers:
        #       - "Host: my.internal.hostname"

volumes:
  data:
#  ssh_drive:

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true