services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - proxy_network
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file=true"
      - "--providers.file.filename=/fileprovider/config.yml"
      # Traefik settings
      - "--log.level=INFO" # level: debug, info, warning, error, critical
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
      - "--serverstransport.insecureskipverify=true" # when forwarding to selfsigned
      # Certificate resolver acme
      - "--certificatesresolvers.letsencrypt.acme.email=$ACME_EMAIL"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      ## Remove comment on acme-staging resolver for testing
      # - "--certificatesResolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      # Configure entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      # SSL Ciphers
      - "--entrypoints.websecure.http.tls.options=default" # from fileprovider
      # middlewares
      - "--entrypoints.websecure.http.middlewares=hsts-header"
      # Enable dashboard
      - "--api=true"
      - "--api.dashboard=$DASHBOARDENABLED"
      - "--api.insecure=false"
    security_opt:
      - no-new-privileges:true
    environment:
      - ACME_EMAIL=$ACME_EMAIL
    configs:
      - source: fileprovider
        target: /fileprovider/config.yml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certs:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik-secure.entrypoints=${DASHBOARD_ENTRYPOINTS:-websecure-internal}"
      - "traefik.http.routers.traefik.rule=Host(`t.$DOMAINNAME`)"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      # important middleware
      - "traefik.http.middlewares.hsts-header.headers.customResponseHeaders.Strict-Transport-Security=max-age=63072000"

configs:
  fileprovider:
    content: |
      tls:
        options:
          default:
            minVersion: VersionTLS12
            cipherSuites:
            # Recommended ciphers for TLSv1.2
            - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
            # Recommended ciphers for TLSv1.3
            - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
          tlsv13only:
            minVersion: VersionTLS13

volumes:
  traefik_certs:

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true