services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - proxy_network
    ports:
      - "80:80"
      - "880:880"
      - "443:443"
      - "4443:4443"
    command:
      # provider setup docker/file
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" # Default is true
      - "--providers.file.filename=/fileprovider/config.yml" # Default is true
      - "--providers.file.watch=true"
      # Traefik settings
      - "--log.level=INFO" # level: debug, info, warning, error, critical
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
      - "--serversTransport.insecureSkipVerify=true" # when forwarding to selfsigned
      # Certificate resolver cloudflare
      - "--certificatesResolvers.cf-staging.acme.email=$CF_API_EMAIL"
      - "--certificatesResolvers.cf-staging.acme.storage=/cloudflare/acme.json"
      - "--certificatesResolvers.cf-staging.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory" # default is production
      - "--certificatesResolvers.cf-staging.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesResolvers.cf-staging.acme.dnsChallenge.resolvers[0]=1.1.1.1:53"
      - "--certificatesResolvers.cf-staging.acme.dnsChallenge.resolvers[1]=1.0.0.1:53"
      - "--certificatesResolvers.cf-production.acme.email=$CF_API_EMAIL"
      - "--certificatesResolvers.cf-production.acme.storage=/cloudflare/acme.json"
      - "--certificatesResolvers.cf-production.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesResolvers.cf-production.acme.dnsChallenge.resolvers[0]=1.1.1.1:53"
      - "--certificatesResolvers.cf-production.acme.dnsChallenge.resolvers[1]=1.0.0.1:53"
      # Configure default entrypoints
      - "--entrypoints.web.address=:880"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:4443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=cf-$CF_STAGING_OR_PRODUCTION"
      - "--entrypoints.websecure.http.tls.domains[0].main=$DOMAINNAME"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.$DOMAINNAME"
      # Configure internal only entrypoints
      - "--entrypoints.web-internal.address=:80"
      - "--entrypoints.web-internal.http.redirections.entrypoint.to=websecure-internal"
      - "--entrypoints.web-internal.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure-internal.address=:443"
      - "--entrypoints.websecure-internal.http.tls=true"
      - "--entrypoints.websecure-internal.http.tls.certResolver=cf-$CF_STAGING_OR_PRODUCTION"
      - "--entrypoints.websecure-internal.http.tls.domains[0].main=$DOMAINNAME"
      - "--entrypoints.websecure-internal.http.tls.domains[0].sans=*.$DOMAINNAME"
      # SSL Ciphers
      - "--entrypoints.websecure.http.tls.options=default" # from fileprovider
      - "--entrypoints.websecure-internal.http.tls.options=default" # from fileprovider
      # middlewares
      - "--entrypoints.websecure.http.middlewares=hsts-header@docker"
      - "--entrypoints.websecure-internal.http.middlewares=hsts-header@docker"
      # crowdsec
      - "--entrypoints.web.http.middlewares=crowdsec-bouncer@docker"
      - "--entrypoints.websecure.http.middlewares=crowdsec-bouncer@docker,hsts-header"
      - "--accessLog=true"
      - "--accessLog.filePath=/var/log/crowdsec/traefik.log"
      - "--accessLog.bufferingSize=100" # Configuring a buffer of 100 lines
      - "--accessLog.filters.statusCodes=204-299,400-499,500-59" # Statut code to log
      # enable dashboard
      - "--api=true"
      - "--api.dashboard=$DASHBOARDENABLED"
      - "--api.insecure=false"
    security_opt:
      - no-new-privileges:true
    # cloudflare stuff
    environment:
      - CF_API_EMAIL=$CF_API_EMAIL
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
    configs:
      - source: fileprovider
        target: /fileprovider/config.yml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${UNIX_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - traefik_certs:/cloudflare
      # crowdsec
      - traefik_access_log:/var/log/crowdsec/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.entrypoints=${DASHBOARD_ENTRYPOINTS:-websecure-internal}"
      - "traefik.http.routers.traefik-secure.rule=Host(`t.$DOMAINNAME`)"
      # important middleware
      - "traefik.http.middlewares.hsts-header.headers.customResponseHeaders.Strict-Transport-Security=max-age=63072000"

  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    restart: unless-stopped
    networks:
      - proxy_network
    # expose:
    #   - 8080
    environment:
      PGID: "1000"
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve"
    configs:
      - source: crowdsec_parser
        target: /etc/crowdsec/acquis.yaml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - traefik_access_log:/var/log/crowdsec:ro
      - crowdsec_db:/var/lib/crowdsec/data
      - crowdsec_config:/etc/crowdsec

  crowdsec-traefik-bouncer:
    depends_on:
      - crowdsec
    image: fbonalair/traefik-crowdsec-bouncer
    container_name: bouncer-traefik
    restart: unless-stopped
    networks:
      - proxy_network
    environment:
      CROWDSEC_BOUNCER_API_KEY: $CROWDSEC_BOUNCER_API_KEY
      CROWDSEC_AGENT_HOST: crowdsec:8080
      GIN_MODE: release
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.crowdsec-bouncer.forwardauth.address=http://bouncer-traefik:8080/api/v1/forwardAuth"
      - "traefik.http.middlewares.crowdsec-bouncer.forwardauth.trustForwardHeader=true"
      - "traefik.http.services.crowdsec-bouncer.loadbalancer.server.port=8080"

configs:
  fileprovider:
    content: |
      tls:
        options:
          default:
            minVersion: VersionTLS12
            cipherSuites:
            # Recommended ciphers for TLSv1.2
            - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
            # Recommended ciphers for TLSv1.3
            - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
          tlsv13only:
            minVersion: VersionTLS13
  crowdsec_parser:
    content: |
      ---
        filenames:
          - /var/log/crowdsec/traefik.log
        labels:
          type: traefik

volumes:
  traefik_certs:
  traefik_access_log:
  crowdsec_db:
  crowdsec_config:

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true
