services:
  # UI dashboard
  dashboard:
    image: netbirdio/dashboard:latest
    restart: unless-stopped
    networks:
      - proxy_network
    environment:
      # Endpoints
      - NETBIRD_MGMT_API_ENDPOINT=https://$NETBIRD_DOMAIN:443
      - NETBIRD_MGMT_GRPC_API_ENDPOINT=https://$NETBIRD_DOMAIN:443
      # OIDC
      - AUTH_AUTHORITY=https://$NETBIRD_AUTH_AUTHORITY
      - AUTH_AUDIENCE=$NETBIRD_AUTH_CLIENT_ID
      - AUTH_CLIENT_ID=$NETBIRD_AUTH_CLIENT_ID
      - USE_AUTH0=false
      - AUTH_SUPPORTED_SCOPES=$NETBIRD_AUTH_SUPPORTED_SCOPES
      - AUTH_REDIRECT_URI=/auth
      - AUTH_SILENT_REDIRECT_URI=/silent-auth
      - NETBIRD_DISABLE_LETSENCRYPT=true
      - NETBIRD_TOKEN_SOURCE=$NETBIRD_TOKEN_SOURCE
      - NGINX_SSL_PORT=443
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    labels:
    - traefik.enable=true
    - traefik.http.routers.netbird-dashboard.rule=Host(`$NETBIRD_DOMAIN`)
    - traefik.http.routers.netbird-dashboard.entrypoints=${TRAEFIK_ENTRYPOINTS:-websecure}
    - traefik.http.services.netbird-dashboard.loadbalancer.server.port=80

  # Signal
  signal:
    image: netbirdio/signal:latest
    restart: unless-stopped
    networks:
      - proxy_network
    volumes:
      - netbird-signal:/var/lib/netbird
    #ports:
    #  - 10000:80
    #      # port and command for Let's Encrypt validation
    #      - 443:443
    #    command: ["--letsencrypt-domain", "", "--log-file", "console"]
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    labels:
    - traefik.enable=true
    - traefik.http.routers.netbird-signal.rule=Host(`$NETBIRD_DOMAIN`) && PathPrefix(`/signalexchange.SignalExchange/`)
    - traefik.http.routers.netbird-signal.entrypoints=${TRAEFIK_ENTRYPOINTS:-websecure}
    - traefik.http.services.netbird-signal.loadbalancer.server.port=80
    - traefik.http.services.netbird-signal.loadbalancer.server.scheme=h2c

  # Relay
  relay:
    image: netbirdio/relay:latest
    restart: unless-stopped
    networks:
      - proxy_network
    environment:
    - NB_LOG_LEVEL=info
    - NB_LISTEN_ADDRESS=:30080
    - NB_EXPOSED_ADDRESS=rels://$RELAY_DOMAIN:443
    - NB_AUTH_SECRET=$RELAY_SECRET
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    labels:
    - traefik.enable=true
    - traefik.http.routers.netbird-relay.entrypoints=${TRAEFIK_ENTRYPOINTS:-websecure}
    - traefik.http.routers.netbird-relay.rule=Host(`$RELAY_DOMAIN`)
    - traefik.http.services.netbird-relay.loadbalancer.server.port=30080

  # Management
  management:
    image: netbirdio/management:latest
    restart: unless-stopped
    networks:
      - proxy_network
    depends_on:
      - dashboard
    command: [
      "--port", "443",
      "--log-file", "console",
      "--disable-anonymous-metrics=$NETBIRD_DISABLE_ANONYMOUS_METRICS",
      "--single-account-mode-domain=$NETBIRD_DOMAIN",
      "--dns-domain=$NETBIRD_MGMT_DNS_DOMAIN",
      "--disable-single-account-mode=$NETBIRD_MGMT_DISABLE_SINGLE_ACCOUNT_MODE"
      ]
    configs:
      - source: management.json
        target: /etc/netbird/management.json
    volumes:
      - netbird-mgmt:/var/lib/netbird
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    labels:
    - traefik.enable=true
    - traefik.http.routers.netbird-api.rule=Host(`$NETBIRD_DOMAIN`) && PathPrefix(`/api`)
    - traefik.http.routers.netbird-api.service=netbird-api
    - traefik.http.routers.netbird-api.entrypoints=${TRAEFIK_ENTRYPOINTS:-websecure}
    - traefik.http.services.netbird-api.loadbalancer.server.port=443
    - traefik.http.routers.netbird-management.rule=Host(`$NETBIRD_DOMAIN`) && PathPrefix(`/management.ManagementService/`)
    - traefik.http.routers.netbird-management.service=netbird-management
    - traefik.http.routers.netbird-management.entrypoints=${TRAEFIK_ENTRYPOINTS:-websecure}
    - traefik.http.services.netbird-management.loadbalancer.server.port=443
    - traefik.http.services.netbird-management.loadbalancer.server.scheme=h2c

volumes:
  netbird-mgmt:
  netbird-signal:
  netbird-config:

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true
