---
apiVersion: v1
kind: Namespace
metadata:
  name: netbird
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged

---
apiVersion: v1
kind: Secret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
type: Opaque
stringData:
  NB_API_KEY: ljlhooknhlhjlppoipuztresdf
