x-default: &default
  restart: 'always'
  logging:
    driver: 'json-file'
    options:
      max-size: '500m'
      max-file: '2'

services:
  uptime-kuma:
    <<: *default
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    networks:
      - proxy_network
    environment:
      - TZ=Europe/Berlin    
    volumes:
      - uptime-kuma:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.rule=Host(`$PUBLIC_HOSTNAME`)"
      - "traefik.http.routers.kuma.entrypoints=$PUBLIC_ENTRYPOINTS"
      - "traefik.http.services.kuma.loadbalancer.server.port=3001"

volumes:
  uptime-kuma:

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true
