---
services:
  alloy:
    image: grafana/alloy:v1.10.1
    container_name: alloy
    hostname: alloy
    restart: unless-stopped
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:4321
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    networks:
      - proxy_network
    # ports:
    #   - "12345:12345"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - alloy_data:/var/lib/alloy/data
      - /:/rootfs:ro
      - /run:/run:ro
      - /var/log:/var/log:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker/:ro
      - /run/udev/data:/run/udev/data:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.alloy.tls=true
      - traefik.http.routers.alloy.rule=Host(`$PUBLIC_HOSTNAME`)
      - traefik.http.routers.alloy.entrypoints=${TRAEFIK_ENTRYPOINTS:-websecure}
      - traefik.http.routers.alloy.service=alloy
      - traefik.http.services.alloy.loadbalancer.server.port=4321
      - traefik.http.services.alloy.loadbalancer.server.scheme=http

volumes:
  alloy_data:
    driver: local

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true