---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: whoami
          image: traefik/whoami
          # Wir zwingen whoami auf Port 8080, da wir kein root mehr sind!
          args:
            - --port=8080
          ports:
            - containerPort: 8080
          # Sicherheit auf Container-Ebene
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
